{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeip.fullname" . }}-cluster-role
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    {{- if .Values.rbac.allowNodesPatchPermission }}
    verbs: [ "get", "patch" ]
    {{- else }}
    verbs: [ "get" ]
    {{- end }}
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create", "delete", "get" ]
{{- end }}
